#ifndef IDEVICE_MACRO_UNDEF_H
#define IDEVICE_MACRO_UNDEF_H

// DEBUG
#undef IDEVICE_DEBUG

// LOG
#undef IDEVICE_LOG_LEVEL
#undef IDEVICE_LOG_E
#undef IDEVICE_LOG_I
#undef IDEVICE_LOG_D
#undef IDEVICE_LOG_V

// ASSERT
#undef IDEVICE_ASSERT

#endif // IDEVICE_MACRO_UNDEF_H
